# Site
name: "Arplane Blog"
title: "Arplane Blog"
description: "Arplane Blog For Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  chayapholroibang:
    name: Chayaphol Roibang
    display_name: Chayaphol Roibang
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: arplane0@outlook.com
    web: https://arplane-socity.github.io
    twitter: https://twitter.com/chayaphol1234
    description: "Arplane Developer"
    
   anonymous:
    name: Anonymous(User)
    display_name: Annonymous(User Blog)
    gravatar: 0bc83cb571cd1c50ba6f3e8a78ef1346
    email: null
    web: null
    twitter: null
    description: "The User Blog Is Not Created By Developer And Not A Arplane Official"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
